DROP TABLE IF EXISTS
	films,
	users,
	film_likes,
	friends,
	film_genres,
	genres,
	mpa_ratings	;

CREATE TABLE IF NOT EXISTS films (
  film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(70) NOT NULL,
  description varchar(200) NOT NULL,
  releaseDate date NOT NULL CHECK (releaseDate >= '1985-12-28'::date AND releaseDate < CURRENT_DATE),
  duration bigint,
  rating_id integer
);

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(50),
  login varchar(20),
  name varchar(20),
  birthday date CHECK (birthday < CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS film_likes (
  film_id bigint,
  user_id bigint,
  PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends (
  user_id bigint,
  friend_id bigint,
  confirmed boolean DEFAULT FALSE,
  PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id bigint,
  genre_id integer,
  PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS genres (
  genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa_ratings (
  rating_id INTEGER UNIQUE PRIMARY KEY,
  rating varchar(10) NOT NULL,
  description varchar(150)
);

ALTER TABLE films ADD CONSTRAINT fk_films_to_rating FOREIGN KEY (rating_id) REFERENCES mpa_ratings (rating_id)
    ON DELETE SET NULL;

ALTER TABLE film_likes ADD CONSTRAINT fk_film_likes_to_films FOREIGN KEY(film_id) REFERENCES films (film_id)
    ON DELETE CASCADE;
ALTER TABLE film_likes ADD CONSTRAINT fk_film_likes_to_users FOREIGN KEY(user_id) REFERENCES users (user_id)
    ON DELETE CASCADE;

ALTER TABLE friends ADD CONSTRAINT fk_friends_user_id_to_users FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE;
ALTER TABLE friends ADD CONSTRAINT fk_friends_friend_id_to_users FOREIGN KEY (friend_id) REFERENCES users (user_id)
    ON DELETE CASCADE;

ALTER TABLE film_genres ADD CONSTRAINT fk_film_genres_to_films FOREIGN KEY (film_id) REFERENCES films (film_id)
    ON DELETE CASCADE;
ALTER TABLE film_genres ADD CONSTRAINT fk_film_genres_to_genres FOREIGN KEY (genre_id) REFERENCES genres (genre_id)
    ON DELETE CASCADE;





